config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  root to: 'public/landing#index'
  resources :graphql, only: %i[create], controller: :graph_ql

  namespace :admin do
    root to: 'schedule#index'

    post 'prints/trigger_generation',
         controller: 'trigger_print_generation',
         action: :create,
         as: :prints_trigger_generation

    resource :schedule, only: %i[index]
    resources :cliparts, except: %i[show]
    resources :cupcake_types, except: %i[show]
    resources :fonts, except: %i[show]
    resources :colors, except: %i[show]
    resources :building_types, except: %i[show]
    resources :industries, except: %i[show]
    resources :orders
    resources :prints, only: %i[index show]
    resources :promotion_codes
  end

  scope module: 'public' do
    get '*path', controller: 'landing', action: :index, as: :landing
  end
end

app/controllers/admin/schedule_controller.rb
# frozen_string_literal: true

module Admin
  class ScheduleController < AdminController
    def index
      display_type
      from
      to
      @collection = grouped_orders
    end

    private

    def grouped_orders
      hash = {}
      orders.each do |order|
        [:ship_at, :bake_at].each do |attribute|
          value = order.public_send(attribute)&.to_date
          next unless value
          hash[value] ||= Set.new
          hash[value] << order
        end
      end
      hash.default = Set.new
      hash
    end

    def orders
      scope
        .where(ship_at: (from..to))
        .or(scope.where(bake_at: (from..to)))
    end

    def scope
      @scope ||= policy_scope(Order)
    end

    def display_type
      @display_type ||=
        case params[:display_type]
        when 'monthly' then :monthly
        else :weekly
        end
    end

    def from
      @from ||= DateTime.parse(params[:from])
    rescue
      @from ||= default_from_time
    end

    def default_from_time
      case display_type
      when :monthly then DateTime.now.beginning_of_month
      else DateTime.now.beginning_of_day
      end
    end

    def to
      @to ||= DateTime.parse(params[:to])
    rescue
      @to ||= default_to_time
    end

    def default_to_time
      case display_type
      when :monthly then DateTime.now.end_of_month
      else 2.weeks.from_now.to_datetime
      end
    end
  end
end

app/views/admin/schedule/index.slim
.col-xs-12
  = form_for admin_root_path, method: :get, html: { class: 'form-inline' } do |f|
    .form-group
      label for="_admin_display_type" Display
      = f.select :display_type, [['Weekly', :weekly], ['Monthly', :monthly]], { selected: params[:display_type] }, value: params[:display_type], class: 'form-control', name: :display_type
    .form-group
      label for="_admin_from" From
      = f.text_field :from, value: params[:from], class: 'form-control', type: :date, name: :from
    .form-group
      label for="_admin_to" To
      = f.text_field :to, value: params[:to], class: 'form-control', type: :date, name: :to
    button type="submit" class="btn btn-default" Submit

.col-xs-12
  hr

.col-xs-12
  = render "admin/schedule/views/#{@display_type}", orders: @collection, filter: @filter, from: @from, to: @to